duckdb/duckdb-r

- README.md
Does this look good or is the logo too tall?
> Change logo to new one

- README.md
Re-include steps on how to develop R with extensions.
> Update extension documentation on readme

- tests/testthat/helper-DBItest.R
- tests/testthat/test-DBItest.R
> chore: Skip DBItest tests if not installed

- src/duckdb/src/catalog/default/default_functions.cpp
- src/duckdb/src/common/operator/cast_operators.cpp
- src/duckdb/src/execution/operator/join/physical_iejoin.cpp
- src/duckdb/src/execution/operator/persistent/physical_batch_insert.cpp
- src/duckdb/src/function/cast/time_casts.cpp
- src/duckdb/src/function/table/version/pragma_version.cpp
- src/duckdb/src/include/duckdb/common/operator/cast_operators.hpp
- src/duckdb/src/include/duckdb/execution/executor.hpp
- src/duckdb/src/include/duckdb/execution/operator/join/physical_iejoin.hpp
- src/duckdb/src/include/duckdb/execution/task_error_manager.hpp
- src/duckdb/src/include/duckdb/storage/checkpoint/row_group_writer.hpp
- src/duckdb/src/include/duckdb/storage/checkpoint/table_data_writer.hpp
- src/duckdb/src/include/duckdb/storage/partial_block_manager.hpp
- src/duckdb/src/include/duckdb/storage/table/row_group.hpp
- src/duckdb/src/include/duckdb/storage/table/row_group_collection.hpp
- src/duckdb/src/parallel/executor.cpp
- src/duckdb/src/planner/binder/expression/bind_lambda.cpp
- src/duckdb/src/storage/checkpoint/row_group_writer.cpp
- src/duckdb/src/storage/checkpoint/table_data_writer.cpp
- src/duckdb/src/storage/data_table.cpp
- src/duckdb/src/storage/local_storage.cpp
- src/duckdb/src/storage/table/column_checkpoint_state.cpp
- src/duckdb/src/storage/table/list_column_data.cpp
- src/duckdb/src/storage/table/row_group.cpp
- src/duckdb/src/storage/table/row_group_collection.cpp
- src/duckdb/src/storage/table/standard_column_data.cpp
Merge pull request duckdb/duckdb#10005 from Tishj/python3_7_optional_issue
Merge pull request duckdb/duckdb#9974 from taniabogatsch/duplicate-lambda-parameters
Merge pull request duckdb/duckdb#9999 from Mytherin/parallelcheckpoint
Merge pull request duckdb/duckdb#9973 from xuke-hat/refine-iejoin
Merge pull request duckdb/duckdb#9984 from hawkfish/tsns-time
Merge pull request duckdb/duckdb#9977 from atacan/swift-readme
> chore: Update vendored sources to duckdb/duckdb@24148408432d05bda7cf86f2736d24920c51577c

- README.md
> docs: Add list of contributors

- .github/workflows/vendor.yaml
- rconfigure.py
- vendor.sh
> ci: Update vendored sources nightly

- DESCRIPTION
- _pkgdown.yml
- man/duckdb-package.Rd
> chore: Change maintainer

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- NEWS.md
- cran-comments.md
- src/duckdb/src/common/local_file_system.cpp
- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)
> CRAN release v0.10.1

- R/backend-dbplyr__duckdb_connection.R
- tests/testthat/test-backend-dbplyr__duckdb_connection.R
adress remaining comments from pull request #122 
- check for missing dots
- add an integration test that uses the window function
> chore: `n_distinct()` followup

- R/backend-dbplyr__duckdb_connection.R
- tests/testthat/test-backend-dbplyr__duckdb_connection.R
> feat: Add dbplyr translations for `clock::date_count_between()`

- src/rfuns.cpp
> feat: Tweak implementation of `r_base::sum()`

- src/Makevars
- src/Makevars.in
- src/Makevars.win
> chore: Strip binary if requested

- src/Makevars
- src/Makevars.in
- src/Makevars.win
- src/install.libs.R
> chore: Move stripping logic to `install.libs.R`

- src/install.libs.R
> chore: Fix stripping call

- src/install.libs.R
> chore: Show file sizes

- src/reltoaltrep.cpp
> feat: Temporarily change `max_expression_depth` during ALTREP evaluation

- R/cpp11.R
- R/relational.R
- src/cpp11.cpp
- src/relational.cpp
Related to tidyverse/duckplyr#172
Add comparison expressions for duckdplyr
> feat: Add comparison expression to relational api

- tests/testthat/test-relational.R
Adds tests for comparison expression in the relational api (added in #457)
> test: Add tests for comparison expression

- DESCRIPTION
- NEWS.md
- cran-comments.md
- patch/0008-Initialize-warning_cb.patch
- src/duckdb/src/main/connection.cpp
- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)
> CRAN release v1.1.2

- cleanup
> fix: Make `cleanup` truly idempotent

- src/utils.cpp
- tests/testthat/test-parquet.R
> fix: Support reading from multiple Parquet files again

- tests/testthat/helper-skip.R
- tests/testthat/test-duckdb-extensions.R
> test: ensure be able to install duckdb extensions on release version
