- vendor.sh
seems like the last update vendor script changed last time the vendor script ran https://github.com/duckdb/duckdb-r/commit/16d50d4bd2e38b454390ffe951e6561f21944f01#diff-5207f4376418838c90f2fbb73b803096a1b41cae984e1c78af0726977a9331c6. Probably because everything gets added and committed, so the change is silently commited.
Now you can pass the surname of the duckdb repo, but the default is duckdb. 
Also, if someone does change the vendor script, the changes are erased when the script is executed to avoid this happening again.
This will fix the broke R scripts on duckdb-main
https://github.com/duckdb/duckdb/actions/runs/6323197765/job/17170295075
> fix vendor script

- R/cpp11.R
- R/relational.R
- src/cpp11.cpp
- src/relational.cpp
Just moving this PR to duckdb-r 
https://github.com/duckdb/duckdb/pull/8730
> feat: Support list of strings for column references in R API

- R/backend-dbplyr__duckdb_connection.R
- man/backend-duckdb.Rd
- tests/testthat/test_arrow_stream.R
- tests/testthat/test_tbl__duckdb_connection.R
> chore: Fix tests when dplyr is missing

- R/dbWriteTable__duckdb_connection_character_data.frame.R
- man/duckdb_connection-class.Rd
- revdep/README.md
- revdep/cran.md
- revdep/problems.md
> fix: Align the argument order of `dbWriteTable()` with the DBI specs

- tests/testthat/test_read.R
prompted by this issue 
https://github.com/duckdb/duckdb/issues/8590
> test: Add csv reading test for `duckdb_read_csv(na.strings = )`

- R/dbQuoteIdentifier__duckdb_connection.R
- tests/testthat/test-dbQuoteIdentifier__duckdb_connection.R
> fix: `DBI::dbQuoteIdentifier()` correctly quotes identifiers that start with a digit

- src/include/rapi.hpp
- src/include/reltoaltrep.hpp
- src/reltoaltrep.cpp
- tests/testthat/test_list.R
This uses the same approach as with alters strings, i.e. `Elt()` materialise all with `VECTOR_ELT(AltrepVectorWrapper::Get(x)->Vector(), i);` 
there is probably a better way involving not forcing materialisation, i.e. an `Elt()` method that would just call `duckdb_r_transform(chunk.data[column_index], dest, dest_offset, chunk.size(), false);`
> feat: Initial ALTREP support for `LIST` logical type

- R/backend-dbplyr__duckdb_connection.R
> fix: `dplyr::tbl()` works again when a Parquet or CSV file is passed instead of a table name

- .Rbuildignore
An invalid regex in the .RbuildIgnore is causing many CI failures. A `*` regex character cannot match the `^` character 0 or more times. 
I've changed it to `.*` but I'm not sure if the original intention is to match everything with the suffix `_files`
> Fix invalid regex in .Rbuildignore

- src/register.cpp
We're using namespace `duckdb` which uses it so it should be fine. I plan to make changes to `duckdb::unordered` map in a separate PR to the duckdb repo. I hope this fixes my CI!
> Remove std:: from unordered_map

- src/include/typesr.hpp
- src/relational.cpp
- src/utils.cpp
Is this a reasonable change? This helps with at least one package with duckplyr.
> feat: Map `NA` to `SQLNULL`

- inst/include/cpp11/r_vector.hpp
- src/reltoaltrep.cpp
- src/scan.cpp
- src/statement.cpp
- src/transform.cpp
Timings for running all tests didn't change too much. Need more investigation if this actually harms performance, will await user reports.
R -q -e 'testthat::test_local()'  12.58s user 1.87s system 95% cpu 15.192 total
R -q -e 'testthat::test_local()'  13.12s user 1.99s system 96% cpu 15.644 total
> fix: Avoid `R CMD check` warning regarding `SETLENGTH()` and `SET_TRUELENGTH()`

- R/backend-dbplyr__duckdb_connection.R
- tests/testthat/test-backend-dbplyr__duckdb_connection.R
This PR attempts to adress #110, implementing `n_distinct()` making use of duckdb's [structs](https://duckdb.org/docs/sql/data_types/struct).
I don't have any experience in writing dbplyr SQL translations, in particular I have no idea of the 'best practices', but I tried to mimic as much from the already existing code as I could.
A couple of notes:
- duckdb's struct fields need to be named. In this case, the naming is irrelevant and I chose to name them 'v1', 'v2', 'v3', ... and so on, depending on the number of arguments passed to `n_distinct()`. If there is an alternative prefered way to do it, please let me know.
- I was making use of `glue::glue()`. Although dbplyr depends on glue, and in this function we are assuming that dbplyr is installed, I am not sure if I am allowed to assume …
> feat: Implement `n_distinct()` for multiple arguments using duckdb structs

- R/dbQuoteLiteral__duckdb_connection.R
- src/include/typesr.hpp
- src/scan.cpp
- src/types.cpp
- src/utils.cpp
This PR changes the DuckDB representation of `difftime` R objects from `TIME` to `INTERVAL`. The reasoning here is that R's difftime can represent way larger time differences than single days, which is what `TIME` is for. This goes wrong if the difftime is longer than one day and one tries for example casting the value to a string.
Here is an example that demonstrates the problem
```R
con <- DBI::dbConnect(duckdb::duckdb())
duckdb::duckdb_register(con, "difftime", data.frame(difftime=structure(710, units = "days", class = "difftime")))
print(DBI::dbGetQuery(con, 'select difftime, difftime::varchar difftime_string from difftime'))
```
Currently, this returns random garbage for the string
```
difftime difftime_string
1 61344000 secs  \xd2\034:00:00
``` 
and triggers an assertion when built …
> Change conversion for difftime to INTERVAL, not TIME

- DESCRIPTION
- R/backend-dbplyr__duckdb_connection.R
- tests/testthat/test-backend-dbplyr__duckdb_connection.R
For isssue #116 
- add translations for clock::add_days() and clock::add_years()
- add associated tests
> feat: Add dbplyr translations for `clock::add_days()`, `clock::add_years()`, `clock::get_day()`, `clock::get_month()`, and `clock::get_year()`

- R/backend-dbplyr__duckdb_connection.R
- tests/testthat/_snaps/backend-dbplyr__duckdb_connection.md
- tests/testthat/test-backend-dbplyr__duckdb_connection.R
* In addition, I adjusted the default value of the digits argument in `round()` to `round(x, digits = 0)` to be consistent with the R default value.
Fixes #146
> feat: `round()` duckdb translation uses `ROUND_EVEN()` instead of `ROUND()`

- R/backend-dbplyr__duckdb_connection.R
- tests/testthat/test-backend-dbplyr__duckdb_connection.R
Fixes typo and adds tests
- fixes #173 
- also accidently fixes `str_flatten()` in a windowed context
> fix: Correct usage of `win_current_group()` instead of `win_current_order()` in SQL translation

- src/transform.cpp
- src/types.cpp
- tests/testthat/_snaps/types.md
- tests/testthat/test-map.R
- tests/testthat/test-types.R
> feat: Support fetching `MAP` type

- R/dbExistsTable__duckdb_connection_ANY.R
- man/duckdb_connection-class.Rd
- **CRAN release 1.0.0-1**
- **fix: Support new `I()` syntax from dbplyr**
> fix: Support new `I()` syntax from dbplyr

- R/backend-dbplyr__duckdb_connection.R
- tests/testthat/test-backend-dbplyr__duckdb_connection.R
> feat: `n_distinct()` supports `na.rm = TRUE` with a single vector argument again

- R/csv.R
- man/duckdb_read_csv.Rd
- tests/testthat/test-read.R
Here is a try for #142
@krlmlr: [You suggested](https://github.com/duckdb/duckdb-r/issues/142#issuecomment-2294792558) to modify the SQL and to use `tbl_function()`.
I do not understand why it is needed. Cannot we just pass temporary to `dbCreateTable()` like I did? Can you please clarify?
Warning: this example will overwrite `test.db` and `iris.csv` files on your disk if present.
```r
library(duckdb)
con <- dbConnect(duckdb(), dbdir = "test.db")
write.csv(iris, "iris.csv", row.names = FALSE)
duckdb_read_csv(con, "iris_temp_false", "iris.csv")
duckdb_read_csv(con, "iris_temp_true", "iris.csv", temporary = TRUE)
dbListTables(con)
dbReadTable(con, "iris_temp_false") |> head()
dbReadTable(con, "iris_temp_true") |> head()
dbDisconnect(con)
```
Check that the temporary table is gone:
```
con …
```
> feat: Add `temporary` argument to `duckdb_read_csv()`

- src/statement.cpp
Closes https://github.com/tidyverse/duckplyr/issues/219.
``` r
library(DBI)
drv <- duckdb::duckdb()
con <- dbConnect(drv)
sql <- "SELECT count(*), date FROM SELECT CAST(time AS date), count(*) GROUP by date;"
dbGetQuery(con, sql)
#> Error: rapi_prepare: Failed to extract statements:
#> Parser Error: syntax error at or near "SELECT"
#> LINE 1: SELECT count(*), date FROM SELECT CAST(time AS date), count(*) GRO...
#>                                    ^
```
<sup>Created on 2024-10-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> feat: Catch and add query context for statement extraction

- DESCRIPTION
- NEWS.md
- cleanup
- cleanup.win
- cran-comments.md
Found the following significant warnings:
/usr/include/c++/14/bits/move.h:222:11: warning: ‘((void (**)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >))this)[2]’ is used uninitialized [-Wuninitialized]
See ‘/home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/duckdb.Rcheck/00install.out’ for details.
* used C++ compiler: ‘g++-14 (Debian 14.2.0-8) 14.2.0’
Check results at: https://cran.r-project.org/web/checks/check_results_duckdb.html
> fledge: CRAN release v1.1.3

- cleanup
Skip cleanup if archive is already exists. 
Closes https://github.com/duckdb/duckdb-r/issues/612.
> fix: Make `./cleanup` script reentrant

- R/cpp11.R
- R/cpp12.R
- R/relational.R
- R/rethrow-gen.R
- src/cpp11.cpp
- src/reltoaltrep.cpp
- tests/testthat/test-relational.R
The purpose of this is to support automatic materialization up to a specific threshold (number of rows or number of cells). Is this perhaps built into the DuckDB library?
For review, the crucial part is https://github.com/duckdb/duckdb-r/pull/1017/files#diff-126b595d21fec2ecd861c9c0dbdb1434973d14eabf3fd0e16339e41070d74410R174-R176 : We add a limit relation with the maximum number of rows that we allow, plus one. If the result is larger, we throw an error.
> feat: Limit automatic materialization by number of rows or number of cells

- src/types.cpp
- tests/testthat/test-date.R
> feat: floor sub-day precision date before casting to int

- R/backend-dbplyr__duckdb_connection.R
- tests/testthat/test-backend-dbplyr__duckdb_connection.R
Closes #993 
Adds translation for median aggregate and window functions.
Apparently aggregate function `median()` works without this translation as it is translated to `percentile_cont` ordered set aggregation function. However, the PR now includes a translation for the aggregation function also as I thought it'd be better to align the function calls. Any thoughts on this @krlmlr ?
> feat: Add translation for `median()`

- R/Result.R
> fix: `dbExecute(con, "CALL ...")` no longer attempts to access the resulting data frame. Use `dbGetQuery(con, "CALL ...")` to access the data

- DESCRIPTION
- NEWS.md
- cran-comments.md
- patch/0015-UMA-1.patch
- patch/0016-UMA-2.patch
- patch/0017-UMA-3.patch
- src/duckdb/extension/core_functions/include/core_functions/aggregate/quantile_state.hpp
- src/duckdb/src/common/types/row/tuple_data_segment.cpp
- src/duckdb/src/execution/operator/csv_scanner/scanner/string_value_scanner.cpp
Found the following significant warnings:
../inst/include/cpp11/R.hpp:54:31: warning: identifier '_xl' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
../inst/include/cpp11/named_arg.hpp:44:29: warning: identifier '_nm' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
duckdb/third_party/httplib/httplib.hpp:3422:43: warning: identifier '_t' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
duckdb/third_party/httplib/httplib.hpp:3437:26: warning: identifier '_t' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
duckdb/third_party/httplib/httplib.hpp:3495:26: warning: identifier …
> fledge: CRAN release v1.2.1
